# Generated by Django 5.1.6 on 2025-03-05 19:56

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=200, verbose_name='category safe URL')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.category', verbose_name='parent of category')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(max_length=50, unique=True, verbose_name='product website ID')),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('slug', models.SlugField(max_length=300, verbose_name='product safe URL')),
                ('description', models.TextField(verbose_name='product description')),
                ('is_active', models.BooleanField(default=True, verbose_name='product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date product created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date product last updated')),
                ('category', mptt.fields.TreeManyToManyField(to='inventory.category')),
            ],
        ),
    ]
